### ISSUE TITLE
Dashboard Call

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#72]
The dashboard call in the api got changed and no longer sends description data. Here's the data we need:

- [x] Oid
- [ ] Name
- [ ] Campaign Name (e.g. People of the Sun)
- [ ] Lantern Year
- [ ] Population
- [ ] Expansion count

Ideally this won't be a separate call from the dashboard. If we wanted to make a new call for the watcher that has the barebone details for that user we really just need the settlement list with the detail above and then which settlement is their current one.

![image](https://user-images.githubusercontent.com/1319995/32408432-a7cdc44c-c165-11e7-8b5f-320cf8dc3059.png)

**Comment by toconnell** [comment]
So, here's the thing.

It takes, at a bare minimum, between 1/5th and 1/4th of a second to initialize a settlement and then serialize it (i.e. pull it from the DB, load it into memory, look up all of its assets and turn it into JSON).

There's always room for optimization, but at a certain point, even to get minimal data, there's always going to be a cost in time.

Once you start adding survivors to it, the initialization time takes longer: a settlement with more than 20 survivors takes a full second to initialize and serialize. Obviously it gets worse from there: your LY 20+ settlements where generations of survivors have lived and died is eventually going to hit two- and then three-second initialize/serialize times, etc.

Eventually, browsers with misguided user-friendliness timeouts are going to start killing dashboard requests (and logging bogus CORS errors or whatever): I actually switched to lists of OIDs because Firefox was timing out requests for "super" users with seven (or more) settlements.

At any rate, I can definitely make a new route (call it 'dashboard_full' or something) that initializes all of the settlements that the user is involved in, but there's no way that call will ever come back in less than a second for any user who has created or is playing in three or more settlements.

@CalebKester Assuming you're comfortable taking the performance hit and the timeout risk, do you want me to do that? If so, I can implement it in the next release (obviously going back to how it was is trivial) and we can have @Chibird12 just switch the dashboard route, etc.

**Comment by toconnell** [comment]
This is related to https://github.com/toconnell/kdm-manager/issues/397, which should be a big part of the resolution of it.

**Comment by toconnell** [comment]
Alright @CalebKester  and @Chibird12  here's what changes in the next API release:

- when you get the user back (e.g. from `/user/dashboard/<oid>`), the `user.campaign` and `user.settlements` elements will still be lists, but they will no longer be lists of OIDs. Rather, they will be lists of dictionaries.
- these dictionaries are basically equivalent to the `settlement.sheet` that you would get back from one of the `/settlement/<action>/<oid>` endpoints, e.g. `get` or `sheet`, etc. They will have MOST of the stuff above: `{name: "Settlement Name", _id: {$oid: <settlement_oid>}, campaign: "people_of_the_sun", expansions: ["sunstalker", "white_box"]...}`
- The `/campaign` route has been updated so that if you POST nothing to it, you get ALL AVAILABLE campaign assets (i.e. a nice list of campaign asset definitions/dictionaries/hashes), so you can hit that endpoint (it'll come back REAL fast) to get all campaign data and then do look-ups as needed.

Holler!

**Comment by toconnell** [comment]
PS, you won't ever get an expansion count, so you'll need to do `settlement.sheet.expansions.length` or similar for that.

**Comment by CalebKester** [comment]
![image](https://user-images.githubusercontent.com/1319995/32856714-3643e32a-ca0b-11e7-8b24-8cbf2f613e2c.png)
back in business!
