### ISSUE TITLE
Multiple Attribute Detail Calls

### ISSUE THREAD

**Issue by CalebKester** [Playing-Indoors/KDM_WWW#76]
`/survivor/set_attribute_detail/<survivor_id>` this is just a single attribute right? i can’t set multiple attribute details?

Could I get either a set_many_attribute_details or (preferably) add support to set_many_attributes so i can just send stats, tokens, gear in one api call?

**Comment by toconnell** [comment]
Correct: `/survivor/set_attribute_detail/<survivor_id>` is just for setting one attribute's modifiers (e.g. you set the gear or the tokens value for a single attrib.

I think the best way to achieve your goal would be to update `/survivor/set_many_attributes/<survivor_id>` so that it accepts an 'attribute_details' key, which is a list of details to fiddle:

```
{
    attributes: [
        {attribute: 'Strength', value: 2},
        {attribute: 'survival', value: 5}
    ],
    attribute_details: [
        {'attribute': 'Luck', 'detail': 'tokens', 'value': 2},
        {'attribute': 'Strength', 'detail': 'gear', 'value': -1}
    ],
}
```

What do you think of that? Will that work for you?

If it does, I can implement that pretty quickly and get it into the next release.

**Comment by toconnell** [comment]
@CalebKester What do you think about the approach above? Can you make that work?

**Comment by toconnell** [comment]
https://github.com/toconnell/kdm-manager/issues/410

**Comment by CalebKester** [comment]
I'm sonic fast now:
![image](https://user-images.githubusercontent.com/1319995/32856750-5b0d874c-ca0b-11e7-8482-276c435ac7ef.png)
